name: Publish package

on:
    push:
      branches:
        [ "main" ]
    workflow_dispatch:
    
jobs:
  build-and-release:

    name: Build and release package
    runs-on: ubuntu-latest
    
    # Use container-based Windows runners
    #runs-on: gha-runner-scale-set-windows

    # Needed to create a tag
    permissions:
      contents: write

    env:
      PACKAGE_NAME: 'Milestone.TA.UPnP'

    steps:
    
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install xmllint
        run: |
            sudo apt-get update
            sudo apt-get install libxml2-utils
      
      #- name: Read .nuspec file
      #  id: read-nuspec
      #  run: |

      #      echo "nuspec=<<EOF_MARKER" 
      #      cat prod/${{env.PACKAGE_NAME}}.nuspec
      #      echo EOF_MARKER
      #      echo '$nuspec'
      #      echo "$nuspec"
      #      echo "nuspec='$nuspec'" >> $GITHUB_OUTPUT

      - name: Extract version from .nuspec
        id: extract-version
        run: echo "version=$(xmllint --xpath 'string(/package/metadata/version)' prod/${{env.PACKAGE_NAME}}.nuspec)" >> "$GITHUB_OUTPUT"


      - name: Use the output
        run: |
          echo "The output value is ${{ steps.extract-version.version }}"
      
