name: Publish package

on:
    pull_request:
    push:
      branches:
        [ "main" ]
    workflow_dispatch:
    
jobs:
  build-and-release:

    name: Build and release package
    runs-on: ubuntu-latest
    
    # Use container-based Windows runners
    #runs-on: gha-runner-scale-set-windows

    # Needed to create a tag
    permissions:
      contents: write

    env:
      PACKAGE_NAME: 'Milestone.TA.UPnP'

    steps:
    
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install xmllint
        run: |
            sudo apt-get update
            sudo apt-get install libxml2-utils
      
      - name: Extract version from .nuspec
        id: extract-version
        shell: pwsh
        run: |
            [xml]$xml = Get-Content .\prod\Milestone.TA.UPnP.nuspec
            $node = $xml.SelectSingleNode("//*[local-name()='version']")
            $ver=$node.InnerText.Split(".")
            Write-Output "ver01=$($ver[0])" >> $Env:GITHUB_OUTPUT
            Write-Output "ver02=$($ver[1])" >> $Env:GITHUB_OUTPUT
            Write-Output "ver03=$($ver[2])" >> $Env:GITHUB_OUTPUT
            Write-Output "ver04=$(if ($ver[3] -eq $null) {1} else {$ver[3]})" >> $Env:GITHUB_OUTPUT


      - name: Use the output
        run: |
          echo "The output value ver01  is ${{steps.extract-version.outputs.ver01}}"
          echo  "Value: ${{join(steps.extract-version.outputs.*, ',')}}"


      - name: If it is PUSH on MAIN - show it
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: |
             echo "PUSH on Main"

      - name: Show some github environment 
        run: |
             echo "github.event_name: ${{ github.event_name }}"
             echo "github.ref_name: ${{ github.ref_name }} "
