name: Publish package

on:
    push:
      branches:
        [ "main" ]
    workflow_dispatch:
    
jobs:
  build-and-release:

    name: Build and release package
    runs-on: ubuntu-latest
    
    # Use container-based Windows runners
    #runs-on: gha-runner-scale-set-windows

    # Needed to create a tag
    permissions:
      contents: write

    env:
      PACKAGE_NAME: 'Milestone.TA.UPnP'

    steps:

      - name: Read .nuspec file
        id: read-nuspec
        run: echo "::set-output name=nuspec::$(cat ${{env.PACKAGE_NAME}}.nuspec)"

      - name: Extract version from .nuspec
        id: extract-version
        run: echo "::set-output name=version::$(xmllint --xpath 'string(/package/metadata/version)' <<< ${{ steps.read-nuspec.outputs.nuspec }})"


      - name: Use the output
        run: |
          echo "The output value is ${{ steps.extract-version.version }}"
      
